### ISSUE TITLE
Update to LLVM 12.0

### ISSUE THREAD

**Issue by polkovnikov** [deech/libclang-static-build#2]
Thanks for your project! Would be great if you update your scripts from using LLVM 10.0 to using 12.0. As I see [on zig page](https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows) they already have prebuilt binaries for 12.0 - [llvm+clang+lld-12.0.0-x86_64-windows-msvc-release-mt.tar.xz](https://ziglang.org/deps/llvm%2bclang%2blld-12.0.0-x86_64-windows-msvc-release-mt.tar.xz).

**Comment by deech** [comment]
This is done. Mind testing and closing the issue if it works?

**Comment by polkovnikov** [comment]
Thanks for upgrading!
It works for me at least on my MSVC 2019. Closing issue.
